### ISSUE TITLE
v1.5.0 does not compile with 2.4.20

### ISSUE THREAD

**Issue by Jan-E** [icing/mod_h2#99]
I only replaced /modules/http2 in the httpd 2.4.20 sources. Part of the buildlog:

    .\h2_util.c(1524) : error C2373: 'h2_casecmpstr' : redefinition; different type modifiers .\h2_util.h(387) : see declaration of 'h2_casecmpstr'
    .\h2_util.c(1524) : error C2491: 'h2_casecmpstr' : definition of dllimport function not allowed
    .\h2_util.c(1538) : error C2373: 'h2_casecmpstrn' : redefinition; different type modifiers .\h2_util.h(388) : see declaration of 'h2_casecmpstrn'
    .\h2_util.c(1538) : error C2491: 'h2_casecmpstrn' : definition of dllimport function not allowed

And, besides that, the *.dsp has to be adjusted to reflect the removal of h2_task_output.c, h2_task_input.c & h2_int_queue.c. But that is Windows only.

**Comment by Jan-E** [comment]
See the PR: https://github.com/icing/mod_h2/pulls

And note that the *.dsp has to have references to h2_bucket_beam.c/obj.

**Comment by icing** [comment]
Thanks for the PR, merged.

The dsp is not in this project and the subversion httpd/trunk should have it.

**Comment by icing** [comment]
Fixed in current master.
