### ISSUE TITLE
Breaks trying to compile on debian

### ISSUE THREAD

**Issue by VeNoMouS** [icing/mod_h2#20]
Used latest git of nghttp2

```
Making all in mod_h2
make[1]: Entering directory '/usr/src/mod_h2/mod_h2'
  CC       mod_h2_la-h2_alt_svc.lo
  CC       mod_h2_la-h2_config.lo
  CC       mod_h2_la-h2_conn.lo
  CC       mod_h2_la-h2_conn_io.lo
  CC       mod_h2_la-h2_ctx.lo
  CC       mod_h2_la-h2_from_h1.lo
  CC       mod_h2_la-h2_h2.lo
  CC       mod_h2_la-h2_h2c.lo
  CC       mod_h2_la-h2_io.lo
  CC       mod_h2_la-h2_io_set.lo
  CC       mod_h2_la-h2_mplx.lo
  CC       mod_h2_la-h2_request.lo
  CC       mod_h2_la-h2_response.lo
  CC       mod_h2_la-h2_session.lo
h2_session.c: In function 'init_callbacks':
h2_session.c:524:52: error: passing argument 2 of 'nghttp2_session_callbacks_set_on_invalid_frame_recv_callback' from incompatible pointer type [-Werror]
     NGH2_SET_CALLBACK(*pcb, on_invalid_frame_recv, on_invalid_frame_recv_cb);
                                                    ^
h2_session.c:510:60: note: in definition of macro 'NGH2_SET_CALLBACK'
 nghttp2_session_callbacks_set_##name##_callback(callbacks, fn)
                                                            ^
In file included from h2_private.h:19:0,
                 from h2_session.c:26:
/usr/include/nghttp2/nghttp2.h:1713:1: note: expected 'nghttp2_on_invalid_frame_recv_callback' but argument is of type 'int (*)(struct nghttp2_session *, const union nghttp2_frame *, uint32_t,  void *)'
 nghttp2_session_callbacks_set_on_invalid_frame_recv_callback(
 ^
h2_session.c: In function 'h2_session_create_int':
h2_session.c:598:9: error: implicit declaration of function 'nghttp2_option_set_recv_client_preface' [-Werror=implicit-function-declaration]
         nghttp2_option_set_recv_client_preface(options, 1);
         ^
cc1: all warnings being treated as errors
Makefile:682: recipe for target 'mod_h2_la-h2_session.lo' failed
make[1]: *** [mod_h2_la-h2_session.lo] Error 1
make[1]: Leaving directory '/usr/src/mod_h2/mod_h2'
Makefile:449: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by VeNoMouS** [comment]
Compiled with nghttp 0.7.15...

**Comment by VeNoMouS** [comment]
https://nghttp2.org/blog/2015/05/16/nghttp2-v1-0-0/ ...... https://nghttp2.org/documentation/package_README.html#migration-from-v0-7-15-or-earlier

**Comment by icing** [comment]
If I understand you correctly, mod_h2 compiles with nghttp2 0.7.5, but not with v1.0.0. This is known, and beside the error you listed, there are other incompatible API changes in nghttp2 1.0.0.

mod_h2 will migrate to nghttp2 1.0.0 once curl has done so (mid June), as there are both dependent on the same nghttp2 version. If you see a need for an earlier change, please explain.

Dependencies and incompatible API changes always will suck...

**Comment by VeNoMouS** [comment]
yes, that is correct

**Comment by icing** [comment]
Closing, issue seems to be solved now.
